#!/usr/bin/env python3
"""Expose normalized 201xxx abilities to the historical SpellDraft Grimoire.

SpellBook.lua scans the native spellbook and then requires metadata from
SpellDraftData. Normalized Aventureros spells deliberately use new IDs, so the
historical SpellData.lua has no direct entry for them. Its name fallback is not
reliable on localized clients (for example Frostbolt vs Descarga de Escarcha).

This tool creates a tiny loose-addon file that aliases each normalized custom
spell ID to the metadata of its native source root and ensures the file loads
immediately after SpellData.lua. The Grimoire can then resolve rarity/class by
ID while still displaying the localized spell name returned by the client.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

ALIAS_FILENAME = "AventurerosCustomSpellData.lua"
SPELLDATA_ENTRY_RE = re.compile(r"^\s*\[(\d+)\]\s*=\s*\{", re.MULTILINE)


class GrimoirePatchError(RuntimeError):
    pass


def load_aliases(resolved_path: Path) -> list[tuple[int, int]]:
    try:
        data = json.loads(resolved_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GrimoirePatchError(f"resolved custom spell registry not found: {resolved_path}") from exc
    except json.JSONDecodeError as exc:
        raise GrimoirePatchError(f"invalid resolved custom spell registry {resolved_path}: {exc}") from exc

    spells = data.get("spells")
    if not isinstance(spells, list) or not spells:
        raise GrimoirePatchError(f"{resolved_path}: expected a non-empty spells list")

    aliases: list[tuple[int, int]] = []
    custom_ids: set[int] = set()
    for index, spell in enumerate(spells):
        if not isinstance(spell, dict):
            raise GrimoirePatchError(f"{resolved_path}: spells[{index}] must be an object")
        try:
            custom_id = int(spell["id"])
            source_id = int(spell["clone_from"])
        except (KeyError, TypeError, ValueError) as exc:
            raise GrimoirePatchError(f"{resolved_path}: malformed spells[{index}]") from exc

        if not 200000 <= custom_id <= 299999:
            raise GrimoirePatchError(f"custom spell ID outside 200000-299999: {custom_id}")
        if custom_id in custom_ids:
            raise GrimoirePatchError(f"duplicate custom spell ID: {custom_id}")
        custom_ids.add(custom_id)
        aliases.append((custom_id, source_id))

    aliases.sort()
    return aliases


def validate_sources(spell_data_path: Path, aliases: list[tuple[int, int]]) -> None:
    if not spell_data_path.is_file():
        raise GrimoirePatchError(f"SpellDraft metadata not found: {spell_data_path}")

    text = spell_data_path.read_text(encoding="utf-8")
    existing = {int(value) for value in SPELLDATA_ENTRY_RE.findall(text)}
    missing = sorted({source for _, source in aliases if source not in existing})
    if missing:
        raise GrimoirePatchError(
            "native source metadata missing from SpellData.lua: "
            + ", ".join(str(value) for value in missing)
        )


def render_alias_file(aliases: list[tuple[int, int]]) -> str:
    lines = [
        "-- Auto-generated by Aventureros de Azeroth.",
        "-- Normalized 201xxx spells reuse their native SpellDraft rarity/class metadata.",
        "SpellDraftData = SpellDraftData or {}",
        "",
    ]
    for custom_id, source_id in aliases:
        lines.append(f"SpellDraftData[{custom_id}] = SpellDraftData[{source_id}]")
    lines.append("")
    return "\n".join(lines)


def patch_toc(toc_path: Path) -> bool:
    if not toc_path.is_file():
        raise GrimoirePatchError(f"SpellDraft TOC not found: {toc_path}")

    original = toc_path.read_text(encoding="utf-8")
    lines = [line for line in original.splitlines() if line.strip() != ALIAS_FILENAME]

    try:
        spell_data_index = next(i for i, line in enumerate(lines) if line.strip() == "SpellData.lua")
    except StopIteration as exc:
        raise GrimoirePatchError(f"{toc_path}: SpellData.lua entry not found") from exc

    lines.insert(spell_data_index + 1, ALIAS_FILENAME)
    patched = "\n".join(lines) + "\n"
    if patched == original:
        return False

    backup = toc_path.with_name(toc_path.name + ".aventureros-original")
    if not backup.exists():
        shutil.copy2(toc_path, backup)
    toc_path.write_text(patched, encoding="utf-8")
    return True


def validate_install(addon_dir: Path, aliases: list[tuple[int, int]]) -> None:
    alias_path = addon_dir / ALIAS_FILENAME
    toc_path = addon_dir / "SpellDraft.toc"
    alias_text = alias_path.read_text(encoding="utf-8")
    toc_lines = [line.strip() for line in toc_path.read_text(encoding="utf-8").splitlines()]

    if ALIAS_FILENAME not in toc_lines:
        raise GrimoirePatchError(f"{toc_path}: custom metadata alias file is not loaded")
    if toc_lines.index(ALIAS_FILENAME) != toc_lines.index("SpellData.lua") + 1:
        raise GrimoirePatchError(f"{toc_path}: custom aliases must load immediately after SpellData.lua")

    missing = [
        custom_id
        for custom_id, source_id in aliases
        if f"SpellDraftData[{custom_id}] = SpellDraftData[{source_id}]" not in alias_text
    ]
    if missing:
        raise GrimoirePatchError(
            "custom Grimoire aliases missing after write: "
            + ", ".join(str(value) for value in missing)
        )


def patch_grimoire(client_dir: Path, resolved_path: Path) -> tuple[int, bool]:
    addon_dir = client_dir / "Interface" / "AddOns" / "SpellDraft"
    spell_data = addon_dir / "SpellData.lua"
    toc = addon_dir / "SpellDraft.toc"
    alias_path = addon_dir / ALIAS_FILENAME

    if not addon_dir.is_dir():
        raise GrimoirePatchError(f"SpellDraft addon directory not found: {addon_dir}")

    aliases = load_aliases(resolved_path)
    validate_sources(spell_data, aliases)

    desired = render_alias_file(aliases)
    alias_changed = not alias_path.is_file() or alias_path.read_text(encoding="utf-8") != desired
    if alias_changed:
        alias_path.write_text(desired, encoding="utf-8")

    toc_changed = patch_toc(toc)
    validate_install(addon_dir, aliases)
    return len(aliases), alias_changed or toc_changed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--client-dir", required=True, type=Path)
    parser.add_argument("--resolved", required=True, type=Path)
    args = parser.parse_args()

    try:
        count, changed = patch_grimoire(
            args.client_dir.expanduser().resolve(),
            args.resolved.expanduser().resolve(),
        )
    except GrimoirePatchError as exc:
        raise SystemExit(f"SpellDraft Grimoire patch aborted: {exc}") from exc

    print("SpellDraft Grimoire custom metadata validated:")
    print(f"  normalized aliases: {count} custom 201xxx -> native metadata")
    print(f"  status: {'patched' if changed else 'already valid'}")
    print(f"  addon file: {ALIAS_FILENAME}")
    print("  localized spell names no longer participate in metadata lookup")
    print("  no C++ rebuild required")


if __name__ == "__main__":
    main()
