#!/usr/bin/env python3
"""Install a small client-side overlay showing package taught spells on cards.

The production SpellChoice addon only receives the offered card IDs, so custom
Aventureros package cards have no visual indication of the spells they grant.
This patch generates a loose-addon helper directly from card_packages.json.
It does not change the historical renderer; it only adds small spell icons at
the right edge of a package card and reuses normal GameTooltip spell tooltips.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
DEFAULT_PACKAGES = TOOLS_DIR.parent / "card_packages.json"
OUTPUT_FILENAME = "AventurerosPackageChoiceUI.lua"


class PackageChoiceUIError(RuntimeError):
    pass


def load_packages(path: Path) -> list[dict]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PackageChoiceUIError(f"cannot read {path}: {exc}") from exc

    packages = raw.get("packages")
    if raw.get("schema_version") != 1 or not isinstance(packages, list):
        raise PackageChoiceUIError(f"{path}: expected schema_version=1 and packages[]")
    return packages


def lua_int_list(values: list[int]) -> str:
    return "{ " + ", ".join(str(int(value)) for value in values) + " }"


def render(packages: list[dict]) -> str:
    lines = [
        "-- Auto-generated by Aventureros de Azeroth.",
        "-- Visual helper for package cards in the historical SpellChoice UI.",
        "SpellDraft = SpellDraft or {}",
        "SpellDraft.PackageChoiceData = {",
    ]

    for package in packages:
        card_id = int(package["card_id"])
        common = [int(value) for value in package.get("teaches", [])]
        by_team = package.get("teaches_by_team", {}) or {}
        lines.append(f"  [{card_id}] = {{")
        lines.append(f"    common = {lua_int_list(common)},")
        lines.append("    byTeam = {")
        for raw_team in sorted(by_team, key=lambda value: int(value)):
            values = [int(value) for value in by_team[raw_team]]
            lines.append(f"      [{int(raw_team)}] = {lua_int_list(values)},")
        lines.append("    },")
        lines.append("  },")

    lines.extend([
        "}",
        "",
        "local MAX_PACKAGE_ICONS = 8",
        "local ICON_SIZE = 30",
        "local ICON_STEP = 34",
        "local refreshTimer = nil",
        "",
        "local function TeamId()",
        "  local faction = UnitFactionGroup and UnitFactionGroup(\"player\")",
        "  if faction == \"Alliance\" then return 0 end",
        "  if faction == \"Horde\" then return 1 end",
        "  return nil",
        "end",
        "",
        "local function ResolveTaught(cardId)",
        "  local spec = SpellDraft.PackageChoiceData[cardId]",
        "  if not spec then return nil end",
        "  local result = {}",
        "  local seen = {}",
        "  local function Append(values)",
        "    for _, spellId in ipairs(values or {}) do",
        "      if not seen[spellId] then",
        "        seen[spellId] = true",
        "        table.insert(result, spellId)",
        "      end",
        "    end",
        "  end",
        "  Append(spec.common)",
        "  local team = TeamId()",
        "  if team ~= nil and spec.byTeam then Append(spec.byTeam[team]) end",
        "  return result",
        "end",
        "",
        "local function EnsureVisual(button, index)",
        "  button.sdPackageIcons = button.sdPackageIcons or {}",
        "  local frame = button.sdPackageIcons[index]",
        "  if frame then return frame end",
        "",
        "  frame = CreateFrame(\"Button\", nil, button)",
        "  frame:SetWidth(ICON_SIZE)",
        "  frame:SetHeight(ICON_SIZE)",
        "  frame:EnableMouse(true)",
        "",
        "  frame.icon = frame:CreateTexture(nil, \"ARTWORK\")",
        "  frame.icon:SetAllPoints(frame)",
        "  frame.icon:SetTexture(\"Interface\\\\Icons\\\\INV_Misc_QuestionMark\")",
        "",
        "  frame.border = frame:CreateTexture(nil, \"OVERLAY\")",
        "  frame.border:SetTexture(\"Interface\\\\Buttons\\\\UI-Quickslot2\")",
        "  frame.border:SetPoint(\"CENTER\", frame, \"CENTER\", 0, 0)",
        "  frame.border:SetWidth(48)",
        "  frame.border:SetHeight(48)",
        "",
        "  frame:SetScript(\"OnEnter\", function(self)",
        "    if not self.spellId then return end",
        "    GameTooltip:SetOwner(self, \"ANCHOR_RIGHT\")",
        "    GameTooltip:SetSpellByID(self.spellId)",
        "    GameTooltip:Show()",
        "  end)",
        "  frame:SetScript(\"OnLeave\", function() GameTooltip:Hide() end)",
        "  frame:RegisterForClicks()",
        "  frame:SetScript(\"OnClick\", function() end)",
        "",
        "  button.sdPackageIcons[index] = frame",
        "  return frame",
        "end",
        "",
        "local function HideAll(button)",
        "  if not button or not button.sdPackageIcons then return end",
        "  for _, frame in ipairs(button.sdPackageIcons) do",
        "    frame.spellId = nil",
        "    frame:Hide()",
        "  end",
        "end",
        "",
        "local function RefreshPackageChoiceIcons()",
        "  for slot = 1, 5 do",
        "    local button = _G[\"SpellChoiceButton\" .. slot]",
        "    if button then",
        "      HideAll(button)",
        "      local cardId = button:GetID()",
        "      local taught = cardId and ResolveTaught(cardId) or nil",
        "      if taught and #taught > 0 and button:IsShown() then",
        "        local count = math.min(#taught, MAX_PACKAGE_ICONS)",
        "        local topOffset = ((count - 1) * ICON_STEP) / 2",
        "        for index = 1, count do",
        "          local spellId = taught[index]",
        "          local frame = EnsureVisual(button, index)",
        "          local _, _, icon = GetSpellInfo(spellId)",
        "          frame.spellId = spellId",
        "          frame.icon:SetTexture(icon or \"Interface\\\\Icons\\\\INV_Misc_QuestionMark\")",
        "          frame:ClearAllPoints()",
        "          frame:SetPoint(\"CENTER\", button, \"RIGHT\", 20, topOffset - ((index - 1) * ICON_STEP))",
        "          frame:SetFrameLevel(button:GetFrameLevel() + 10)",
        "          frame:Show()",
        "        end",
        "      end",
        "    end",
        "  end",
        "end",
        "",
        "local function ScheduleRefresh(delay)",
        "  if refreshTimer then refreshTimer:Hide() end",
        "  local timer = refreshTimer or CreateFrame(\"Frame\")",
        "  refreshTimer = timer",
        "  timer.elapsed = 0",
        "  timer.delay = delay or 0.6",
        "  timer:SetScript(\"OnUpdate\", function(self, elapsed)",
        "    self.elapsed = self.elapsed + elapsed",
        "    if self.elapsed >= self.delay then",
        "      self:Hide()",
        "      self:SetScript(\"OnUpdate\", nil)",
        "      RefreshPackageChoiceIcons()",
        "    end",
        "  end)",
        "  timer:Show()",
        "end",
        "",
        "local events = CreateFrame(\"Frame\")",
        "events:RegisterEvent(\"CHAT_MSG_ADDON\")",
        "events:RegisterEvent(\"PLAYER_ENTERING_WORLD\")",
        "events:SetScript(\"OnEvent\", function(self, event, prefix)",
        "  if event == \"CHAT_MSG_ADDON\" and prefix == \"SpellChoice\" then",
        "    ScheduleRefresh(0.6)",
        "  elseif event == \"PLAYER_ENTERING_WORLD\" then",
        "    ScheduleRefresh(1.0)",
        "  end",
        "end)",
        "",
        "if SpellChoiceFrame and SpellChoiceFrame.HookScript then",
        "  SpellChoiceFrame:HookScript(\"OnShow\", function() ScheduleRefresh(0.6) end)",
        "  SpellChoiceFrame:HookScript(\"OnHide\", function()",
        "    for slot = 1, 5 do HideAll(_G[\"SpellChoiceButton\" .. slot]) end",
        "  end)",
        "end",
        "",
    ])
    return "\n".join(lines)


def patch_toc(toc: Path) -> bool:
    if not toc.is_file():
        raise PackageChoiceUIError(f"SpellDraft TOC not found: {toc}")

    original = toc.read_text(encoding="utf-8", errors="replace")
    lines = [line for line in original.splitlines() if line.strip() != OUTPUT_FILENAME]
    try:
        index = next(i for i, line in enumerate(lines) if line.strip() == "SpellChoice.lua")
    except StopIteration as exc:
        raise PackageChoiceUIError(f"{toc}: SpellChoice.lua entry not found") from exc

    lines.insert(index + 1, OUTPUT_FILENAME)
    patched = "\n".join(lines) + "\n"
    if patched == original:
        return False

    backup = toc.with_name(toc.name + ".aventureros-package-ui-original")
    if not backup.exists():
        shutil.copy2(toc, backup)
    toc.write_text(patched, encoding="utf-8")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--client-dir", required=True, type=Path)
    parser.add_argument("--packages", type=Path, default=DEFAULT_PACKAGES)
    args = parser.parse_args()

    try:
        packages = load_packages(args.packages.expanduser().resolve())
        addon = args.client_dir.expanduser().resolve() / "Interface" / "AddOns" / "SpellDraft"
        if not addon.is_dir():
            raise PackageChoiceUIError(f"SpellDraft addon directory not found: {addon}")

        output = addon / OUTPUT_FILENAME
        desired = render(packages)
        changed = not output.is_file() or output.read_text(encoding="utf-8", errors="replace") != desired
        if changed:
            output.write_text(desired, encoding="utf-8")
        toc_changed = patch_toc(addon / "SpellDraft.toc")

        toc_lines = [
            line.strip()
            for line in (addon / "SpellDraft.toc").read_text(encoding="utf-8", errors="replace").splitlines()
        ]
        if OUTPUT_FILENAME not in toc_lines:
            raise PackageChoiceUIError("generated package UI helper is not loaded by SpellDraft.toc")
    except (PackageChoiceUIError, KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"SpellDraft package choice UI patch aborted: {exc}") from exc

    print("SpellDraft package choice UI validated:")
    print(f"  package cards with visual teach metadata: {len(packages)}")
    print(f"  addon file: {OUTPUT_FILENAME}")
    print(f"  status: {'patched' if changed or toc_changed else 'already valid'}")
    print("  taught spells render as tooltip-enabled square icons to the right of package cards")


if __name__ == "__main__":
    main()
