#!/usr/bin/env python3
"""Bridge authoritative server combo points into the WotLK client UI.

The 3.3.5a client keeps GetComboPoints() at zero for the custom Adventurer
class ID 10 even though AzerothCore correctly tracks combo points and sends its
native combo packet. The stock ComboFrame itself is class-agnostic, so this
compatibility layer only replaces GetComboPoints("player", "target") after an
Aventureros server sync has been received. Every other query delegates to the
original client API.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

COMBO_FILENAME = "AventurerosComboPoints.lua"
TOC_FILENAME = "SpellDraft.toc"
ANCHORS = ("AventurerosCustomSpellData.lua", "SpellData.lua")

COMBO_LUA = r'''-- Auto-generated by Aventureros de Azeroth.
-- Class 10 compatibility: use the server's authoritative combo-point state.

local AVENTUREROS_COMBO_PREFIX = "AventurerosCombo"
local NativeGetComboPoints = GetComboPoints
local ServerComboPoints = 0
local HasServerComboSync = false

if RegisterAddonMessagePrefix then
    RegisterAddonMessagePrefix(AVENTUREROS_COMBO_PREFIX)
end

local function IsPlayerTargetComboQuery(unit, target)
    local isPlayer = unit == "player" or (PlayerFrame and unit == PlayerFrame.unit)
    return isPlayer and target == "target"
end

GetComboPoints = function(unit, target)
    if HasServerComboSync and IsPlayerTargetComboQuery(unit, target) then
        return ServerComboPoints
    end

    return NativeGetComboPoints(unit, target)
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("CHAT_MSG_ADDON")
frame:SetScript("OnEvent", function(_, event, prefix, message)
    if event ~= "CHAT_MSG_ADDON" or prefix ~= AVENTUREROS_COMBO_PREFIX then
        return
    end

    local points = tonumber(message)
    if not points then
        return
    end

    points = math.floor(points)
    if points < 0 then
        points = 0
    elseif points > 5 then
        points = 5
    end

    ServerComboPoints = points
    HasServerComboSync = true

    if ComboFrame_Update then
        ComboFrame_Update()
    end
end)
'''


class ComboPatchError(RuntimeError):
    pass


def patch_toc(toc_path: Path) -> bool:
    if not toc_path.is_file():
        raise ComboPatchError(f"SpellDraft TOC not found: {toc_path}")

    original = toc_path.read_text(encoding="utf-8")
    lines = [line for line in original.splitlines() if line.strip() != COMBO_FILENAME]

    insert_after = None
    for anchor in ANCHORS:
        for index, line in enumerate(lines):
            if line.strip() == anchor:
                insert_after = index
                break
        if insert_after is not None:
            break

    if insert_after is None:
        raise ComboPatchError(
            f"{toc_path}: neither AventurerosCustomSpellData.lua nor SpellData.lua was found"
        )

    lines.insert(insert_after + 1, COMBO_FILENAME)
    patched = "\n".join(lines) + "\n"
    if patched == original:
        return False

    backup = toc_path.with_name(toc_path.name + ".aventureros-original")
    if not backup.exists():
        shutil.copy2(toc_path, backup)
    toc_path.write_text(patched, encoding="utf-8")
    return True


def validate_install(addon_dir: Path) -> None:
    combo_path = addon_dir / COMBO_FILENAME
    toc_path = addon_dir / TOC_FILENAME

    if not combo_path.is_file():
        raise ComboPatchError(f"combo bridge was not written: {combo_path}")

    text = combo_path.read_text(encoding="utf-8")
    required = (
        'local AVENTUREROS_COMBO_PREFIX = "AventurerosCombo"',
        "local NativeGetComboPoints = GetComboPoints",
        "GetComboPoints = function(unit, target)",
        'frame:RegisterEvent("CHAT_MSG_ADDON")',
        "ComboFrame_Update()",
    )
    missing = [value for value in required if value not in text]
    if missing:
        raise ComboPatchError(
            f"{combo_path}: incomplete combo bridge: " + ", ".join(missing)
        )

    toc_lines = [line.strip() for line in toc_path.read_text(encoding="utf-8").splitlines()]
    if toc_lines.count(COMBO_FILENAME) != 1:
        raise ComboPatchError(
            f"{toc_path}: expected exactly one {COMBO_FILENAME} entry"
        )


def patch_combo_ui(client_dir: Path) -> bool:
    addon_dir = client_dir / "Interface" / "AddOns" / "SpellDraft"
    if not addon_dir.is_dir():
        raise ComboPatchError(f"SpellDraft addon directory not found: {addon_dir}")

    combo_path = addon_dir / COMBO_FILENAME
    combo_changed = not combo_path.is_file() or combo_path.read_text(encoding="utf-8") != COMBO_LUA
    if combo_changed:
        combo_path.write_text(COMBO_LUA, encoding="utf-8")

    toc_changed = patch_toc(addon_dir / TOC_FILENAME)
    validate_install(addon_dir)
    return combo_changed or toc_changed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--client-dir", required=True, type=Path)
    args = parser.parse_args()

    try:
        changed = patch_combo_ui(args.client_dir.expanduser().resolve())
    except ComboPatchError as exc:
        raise SystemExit(f"SpellDraft combo UI patch aborted: {exc}") from exc

    print("SpellDraft Adventurer combo-point compatibility validated:")
    print(f"  status: {'patched' if changed else 'already valid'}")
    print(f"  addon file: {COMBO_FILENAME}")
    print("  server state overrides only GetComboPoints(player, target)")
    print("  Blizzard ComboFrame remains the visible UI")
    print("  requires the matching rebuilt mod-spelldraft server")


if __name__ == "__main__":
    main()
