#!/usr/bin/env python3
"""Install compact profile-aware client scaling for normalized 201xxx spells.

The client receives native rank anchors, not serialized 1..60 tables. Damage,
cast time and duration are interpolated locally with the same rules used by the
server generator.

Periodic damage is interpolated PER TICK. The visible DoT total is derived as
integer tick amount * tick count, exactly matching what AzerothCore executes.
Native dot_total values remain in the semantic registry for validation, but are
not independently interpolated by the client.
"""

from __future__ import annotations

import argparse
import json
import shutil
import struct
from pathlib import Path
from typing import Any

from patch_adventurer_class_dbcs import read_dbc, u32
from patch_spelldraft_scaled_tooltips import render_compat_lua

DATA_FILENAME = "AventurerosSpellScaling.lua"
COMPAT_FILENAME = "AventurerosScaledTooltipCompat.lua"
PROFILE_TOOLTIP_FILENAME = "AventurerosProfiledTooltip.lua"
TOOLTIP_FILENAME = "ScaledSpellTooltips.lua"
LEGACY_FILENAMES = {"CustomSpellScaling.lua", "SpellDamageCurves.lua"}

SPELL_ID = 0
EFFECT_DIE_SIDES = 74
EFFECT_BASE_POINTS = 80


class TooltipError(RuntimeError):
    pass


def i32(row: bytes | bytearray, field: int) -> int:
    return struct.unpack_from("<i", row, field * 4)[0]


def load_profiles(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise TooltipError(f"profile registry not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise TooltipError(f"invalid profile registry {path}: {exc}") from exc
    if not isinstance(data, dict) or int(data.get("version", 0)) != 2:
        raise TooltipError(f"{path}: expected profile registry version 2")
    if data.get("periodic_model") != "per_tick_integer_interpolation":
        raise TooltipError(f"{path}: unexpected or missing periodic_model")
    spells = data.get("spells")
    if not isinstance(spells, list) or not spells:
        raise TooltipError(f"{path}: expected a non-empty spells list")
    return data


def spell_rows(path: Path) -> dict[int, bytearray]:
    _fields, _record_size, records, _strings, _trailing = read_dbc(path)
    return {u32(row, SPELL_ID): row for row in records}


def amount_anchor_text(anchors: list[dict[str, Any]], field: str) -> str:
    values: list[str] = []
    for anchor in anchors:
        amount = anchor.get(field)
        if not isinstance(amount, dict):
            continue
        values.append(
            "{%d, %d, %d}"
            % (
                int(anchor["level"]),
                int(amount["min"]),
                int(amount["max"]),
            )
        )
    return "{" + ", ".join(values) + "}"


def scalar_anchor_text(anchors: list[dict[str, Any]], field: str) -> str:
    values = [
        "{%d, %d}" % (int(anchor["level"]), int(anchor[field]))
        for anchor in anchors
        if field in anchor
    ]
    return "{" + ", ".join(values) + "}"


def render_data_lua(
    data: dict[str, Any],
    dbc_rows: dict[int, bytearray],
) -> tuple[str, int, int]:
    max_level = int(data["runtime_max_level"])
    low_level_offset = float(data.get("low_level_offset", 0.0))
    spells = data["spells"]

    lines = [
        "-- Auto-generated by Aventureros de Azeroth.",
        "-- Profile-aware native-rank anchors; no 1..60 tables are serialized.",
        "SpellDraft = SpellDraft or {}",
        "SpellDraftCustomSpellAliases = {}",
        "SpellDraftCustomScaling = {}",
        "SpellDraftDamageCurves = {}",
        "SpellDraftProfiledCastTimes = {}",
        "",
        f"local AVENTUREROS_MAX_LEVEL = {max_level}",
        f"local AVENTUREROS_LOW_LEVEL_OFFSET = {low_level_offset!r}",
        "",
        "local function RoundInt(value)",
        "  if value >= 0 then return math.floor(value + 0.5) end",
        "  return -math.floor(math.abs(value) + 0.5)",
        "end",
        "",
        "local function RoundQuantum(value, quantum)",
        "  if not quantum or quantum <= 1 then return RoundInt(value) end",
        "  return math.floor(value / quantum + 0.5) * quantum",
        "end",
        "",
        "local function SignedScaled(value, ratio)",
        "  if value == 0 then return 0 end",
        "  local magnitude = math.max(1, math.floor(math.abs(value) * ratio + 0.5))",
        "  if value > 0 then return magnitude end",
        "  return -magnitude",
        "end",
        "",
        "local function BuildAmountPoints(anchors)",
        "  if not anchors or #anchors == 0 then return {} end",
        "  if anchors[1][1] <= 1 then return anchors end",
        "  local first = anchors[1]",
        "  local ratio = (1 + AVENTUREROS_LOW_LEVEL_OFFSET) / (first[1] + AVENTUREROS_LOW_LEVEL_OFFSET)",
        "  local points = {{1, SignedScaled(first[2], ratio), SignedScaled(first[3], ratio)}}",
        "  for i = 1, #anchors do points[#points + 1] = anchors[i] end",
        "  return points",
        "end",
        "",
        "local function InterpolateAmount(points, level)",
        "  if not points or #points == 0 then return nil end",
        "  if level <= points[1][1] then return points[1][2], points[1][3] end",
        "  if level >= points[#points][1] then return points[#points][2], points[#points][3] end",
        "  for i = 1, #points - 1 do",
        "    local left = points[i]",
        "    local right = points[i + 1]",
        "    if level >= left[1] and level <= right[1] then",
        "      local t = (level - left[1]) / (right[1] - left[1])",
        "      local minimum = RoundInt(left[2] + (right[2] - left[2]) * t)",
        "      local maximum = RoundInt(left[3] + (right[3] - left[3]) * t)",
        "      if maximum < minimum then minimum, maximum = maximum, minimum end",
        "      return minimum, maximum",
        "    end",
        "  end",
        "end",
        "",
        "local function InterpolateScalar(anchors, level, quantum)",
        "  if not anchors or #anchors == 0 then return nil end",
        "  if level <= anchors[1][1] then return anchors[1][2] end",
        "  if level >= anchors[#anchors][1] then return anchors[#anchors][2] end",
        "  for i = 1, #anchors - 1 do",
        "    local left = anchors[i]",
        "    local right = anchors[i + 1]",
        "    if level >= left[1] and level <= right[1] then",
        "      local t = (level - left[1]) / (right[1] - left[1])",
        "      return RoundQuantum(left[2] + (right[2] - left[2]) * t, quantum)",
        "    end",
        "  end",
        "end",
        "",
        "local function ClampLevel(level)",
        "  level = tonumber(level) or UnitLevel(\"player\") or 1",
        "  level = math.floor(level)",
        "  if level < 1 then level = 1 end",
        "  if level > AVENTUREROS_MAX_LEVEL then level = AVENTUREROS_MAX_LEVEL end",
        "  return level",
        "end",
        "",
        "local function MakeRanges(anchors)",
        "  local points = BuildAmountPoints(anchors)",
        "  return setmetatable({}, {",
        "    __index = function(cache, requestedLevel)",
        "      local level = ClampLevel(requestedLevel)",
        "      local minimum, maximum = InterpolateAmount(points, level)",
        "      if minimum == nil then return nil end",
        "      local value = {minimum, maximum}",
        "      rawset(cache, requestedLevel, value)",
        "      return value",
        "    end,",
        "  })",
        "end",
        "",
        "local function MakeDots(tickAmountAnchors, durationAnchors, tickMsAnchors)",
        "  local tickAmounts = BuildAmountPoints(tickAmountAnchors)",
        "  return setmetatable({}, {",
        "    __index = function(cache, requestedLevel)",
        "      local level = ClampLevel(requestedLevel)",
        "      local tickMin, tickMax = InterpolateAmount(tickAmounts, level)",
        "      local durationMs = InterpolateScalar(durationAnchors, level, 1000)",
        "      local tickMs = InterpolateScalar(tickMsAnchors, level, 1)",
        "      if tickMin == nil or durationMs == nil or not tickMs or tickMs <= 0 then return nil end",
        "      local ticks = 1",
        "      if durationMs > 0 then ticks = math.max(1, math.floor(durationMs / tickMs)) end",
        "      local totalMin = tickMin * ticks",
        "      local totalMax = tickMax * ticks",
        "      local total = totalMin",
        "      if totalMax ~= totalMin then total = RoundInt((totalMin + totalMax) / 2) end",
        "      local value = {total = total, duration = durationMs / 1000}",
        "      rawset(cache, requestedLevel, value)",
        "      return value",
        "    end,",
        "  })",
        "end",
        "",
        "local function MakeScalar(anchors, quantum)",
        "  return setmetatable({}, {",
        "    __index = function(cache, requestedLevel)",
        "      local level = ClampLevel(requestedLevel)",
        "      local value = InterpolateScalar(anchors, level, quantum)",
        "      rawset(cache, requestedLevel, value)",
        "      return value",
        "    end,",
        "  })",
        "end",
        "",
    ]

    aliases = 0
    curves = 0
    for spell in spells:
        if not isinstance(spell, dict):
            continue
        custom_id = int(spell["id"])
        source_id = int(spell["clone_from"])
        lines.append(f"SpellDraftCustomSpellAliases[{custom_id}] = {source_id}")
        aliases += 1

    lines.extend(
        [
            "",
            "function SpellDraft.GetCustomSpellSourceID(spellID)",
            "  return SpellDraftCustomSpellAliases[tonumber(spellID)]",
            "end",
            "",
            "function SpellDraft.GetProfiledCastTime(spellID, level)",
            "  local values = SpellDraftProfiledCastTimes[tonumber(spellID)]",
            "  if not values then return nil end",
            "  return values[ClampLevel(level)]",
            "end",
            "",
        ]
    )

    for spell in spells:
        if not isinstance(spell, dict):
            continue
        custom_id = int(spell["id"])
        profile = str(spell.get("profile", "generic"))
        anchors = spell.get("anchors")
        if not isinstance(anchors, list) or not anchors:
            continue

        cast_text = scalar_anchor_text(anchors, "cast_ms")
        lines.append(
            f"SpellDraftProfiledCastTimes[{custom_id}] = MakeScalar({cast_text}, 100)"
        )

        direct_index = spell.get("direct_effect_index")
        if direct_index is None or profile not in {"direct_damage", "damage_with_dot"}:
            continue
        direct_index = int(direct_index)
        direct_text = amount_anchor_text(anchors, "direct")
        if direct_text == "{}":
            continue

        custom_row = dbc_rows.get(custom_id)
        if custom_row is None:
            raise TooltipError(f"custom spell {custom_id} missing from Spell.dbc")
        static_base = i32(custom_row, EFFECT_BASE_POINTS + direct_index)
        static_die = i32(custom_row, EFFECT_DIE_SIDES + direct_index)
        legacy_profile = (
            "spell_damage_with_dots" if profile == "damage_with_dot" else "spell_damage"
        )

        lines.append(f"SpellDraftCustomScaling[{custom_id}] = {{")
        lines.append(f"  profile = \"{legacy_profile}\",")
        lines.append("  baseLevel = 1,")
        lines.append(f"  maxLevel = {max_level},")
        lines.append("  effects = {{")
        lines.append("    {")
        lines.append(f"      index = {direct_index + 1},")
        lines.append(f"      basePoints = {static_base},")
        lines.append(f"      dieSides = {static_die},")
        lines.append("      realPointsPerLevel = 0,")
        lines.append("    },")
        lines.append("  },")
        lines.append("}")
        lines.append(f"SpellDraftDamageCurves[{custom_id}] = {{")
        lines.append(f"  profile = \"{legacy_profile}\",")
        lines.append(f"  maxLevel = {max_level},")
        lines.append(f"  ranges = MakeRanges({direct_text}),")

        if profile == "damage_with_dot":
            dot_tick_text = amount_anchor_text(anchors, "dot_tick")
            duration_text = scalar_anchor_text(anchors, "duration_ms")
            tick_ms_text = scalar_anchor_text(anchors, "tick_ms")
            if (
                dot_tick_text != "{}"
                and duration_text != "{}"
                and tick_ms_text != "{}"
            ):
                lines.append(
                    f"  dots = MakeDots({dot_tick_text}, {duration_text}, {tick_ms_text}),"
                )
        lines.append("}")
        curves += 1

    lines.append("")
    return "\n".join(lines), aliases, curves


def render_profile_tooltip_lua() -> str:
    return r'''-- Auto-generated by Aventureros de Azeroth.
-- Rewrites only the visible cast-time line for profile-aware 201xxx spells.
SpellDraft = SpellDraft or {}

local function TooltipSpellID(tip)
  if not tip or not tip.GetSpell then return nil end
  local _name, second, third = tip:GetSpell()
  local id = tonumber(third) or tonumber(second)
  if not id then return nil end
  if not SpellDraftCustomSpellAliases or not SpellDraftCustomSpellAliases[id] then return nil end
  return id
end

local function SecondsText(ms)
  if not ms then return nil end
  if ms % 1000 == 0 then return tostring(ms / 1000) end
  return string.format("%.1f", ms / 1000)
end

local function UpdateProfiledCastLine(tip)
  local spellID = TooltipSpellID(tip)
  if not spellID or not SpellDraft.GetProfiledCastTime then return end
  local castMs = SpellDraft.GetProfiledCastTime(spellID, UnitLevel("player"))
  if not castMs or castMs <= 0 then return end

  local replacement = SecondsText(castMs)
  if not replacement then return end

  local name = tip:GetName()
  if not name then return end
  local count = math.min(tip:NumLines() or 0, 7)
  for i = 2, count do
    local left = _G[name .. "TextLeft" .. i]
    if left then
      local text = left:GetText()
      -- WotLK cast lines begin with the numeric seconds value (for example
      -- "1.5 s para lanzar"). Description durations occur later in prose.
      if text and text:match("^%d+[%.%d]* s%s") then
        local changed, n = text:gsub("^%d+[%.%d]* s", replacement .. " s", 1)
        if n > 0 then left:SetText(changed) end
        return
      end
    end
  end
end

local function HookTooltip(tip)
  if tip and tip.HookScript then tip:HookScript("OnTooltipSetSpell", UpdateProfiledCastLine) end
end

HookTooltip(GameTooltip)
HookTooltip(ItemRefTooltip)
'''


def patch_toc(path: Path) -> bool:
    if not path.is_file():
        raise TooltipError(f"SpellDraft TOC not found: {path}")
    original = path.read_text(encoding="utf-8")
    removable = LEGACY_FILENAMES | {
        DATA_FILENAME,
        COMPAT_FILENAME,
        PROFILE_TOOLTIP_FILENAME,
    }
    lines = [line for line in original.splitlines() if line.strip() not in removable]
    try:
        tooltip_index = next(
            i for i, line in enumerate(lines) if line.strip() == TOOLTIP_FILENAME
        )
    except StopIteration as exc:
        raise TooltipError(f"{path}: {TOOLTIP_FILENAME} entry not found") from exc

    lines.insert(tooltip_index, DATA_FILENAME)
    lines.insert(tooltip_index + 2, COMPAT_FILENAME)
    lines.insert(tooltip_index + 3, PROFILE_TOOLTIP_FILENAME)
    patched = "\n".join(lines) + "\n"
    if patched == original:
        return False
    backup = path.with_name(path.name + ".aventureros-original")
    if not backup.exists():
        shutil.copy2(path, backup)
    path.write_text(patched, encoding="utf-8")
    return True


def validate(addon_dir: Path, aliases: int, curves: int) -> None:
    toc = [
        line.strip()
        for line in (addon_dir / "SpellDraft.toc").read_text(encoding="utf-8").splitlines()
    ]
    for filename in (
        DATA_FILENAME,
        TOOLTIP_FILENAME,
        COMPAT_FILENAME,
        PROFILE_TOOLTIP_FILENAME,
    ):
        if toc.count(filename) != 1:
            raise TooltipError(f"expected exactly one {filename} in SpellDraft.toc")
    for legacy in LEGACY_FILENAMES:
        if legacy in toc:
            raise TooltipError(f"legacy tooltip curve still loaded: {legacy}")
    if toc.index(DATA_FILENAME) + 1 != toc.index(TOOLTIP_FILENAME):
        raise TooltipError(f"{DATA_FILENAME} must load immediately before {TOOLTIP_FILENAME}")
    if toc.index(COMPAT_FILENAME) != toc.index(TOOLTIP_FILENAME) + 1:
        raise TooltipError(f"{COMPAT_FILENAME} must load immediately after {TOOLTIP_FILENAME}")
    if toc.index(PROFILE_TOOLTIP_FILENAME) != toc.index(COMPAT_FILENAME) + 1:
        raise TooltipError(f"{PROFILE_TOOLTIP_FILENAME} must load after compatibility formatter")
    if aliases <= 0 or curves <= 0:
        raise TooltipError("generated profile tooltip data is empty")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--client-dir", required=True, type=Path)
    parser.add_argument("--profiles", required=True, type=Path)
    parser.add_argument("--dbc-dir", required=True, type=Path)
    args = parser.parse_args()

    client = args.client_dir.expanduser().resolve()
    addon_dir = client / "Interface" / "AddOns" / "SpellDraft"
    if not addon_dir.is_dir():
        raise SystemExit(f"SpellDraft addon directory not found: {addon_dir}")

    try:
        data = load_profiles(args.profiles.expanduser().resolve())
        rows = spell_rows(args.dbc_dir.expanduser().resolve() / "Spell.dbc")
        data_lua, aliases, curves = render_data_lua(data, rows)
        compat_lua = render_compat_lua()
        profile_lua = render_profile_tooltip_lua()

        changed = False
        desired = {
            DATA_FILENAME: data_lua,
            COMPAT_FILENAME: compat_lua,
            PROFILE_TOOLTIP_FILENAME: profile_lua,
        }
        for filename, content in desired.items():
            path = addon_dir / filename
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                path.write_text(content, encoding="utf-8")
                changed = True
        if patch_toc(addon_dir / "SpellDraft.toc"):
            changed = True
        validate(addon_dir, aliases, curves)
    except (KeyError, TypeError, ValueError, TooltipError) as exc:
        raise SystemExit(f"Profiled SpellDraft tooltip patch aborted: {exc}") from exc

    print("SpellDraft profile-aware tooltip scaling validated:")
    print(f"  aliases: {aliases}")
    print(f"  direct/damage+dot curves: {curves}")
    print("  periodic model: same integer per-tick interpolation as server runtime")
    print("  visible DoT total: runtime tick amount x runtime tick count")
    print("  values: direct damage + DoT total + duration + cast time")
    print("  storage: native anchors only; client interpolates current level")
    print(f"  status: {'patched' if changed else 'already valid'}")
    print("  legacy per-level Lua curves: not loaded")


if __name__ == "__main__":
    main()
