#!/usr/bin/env python3
"""Bridge authoritative Adventurer combo points into the WotLK ComboFrame.

The 3.3.5a client keeps its native GetComboPoints() API at zero for custom
class ID 10 even though AzerothCore correctly owns the combo-point state.

Do NOT replace GetComboPoints(): that global participates in Blizzard UI code
and overriding it from an addon can taint protected actions. Instead, receive
the authoritative server count and render it directly through Blizzard's
existing ComboFrame/ComboPoint textures. The native API remains untouched.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

COMBO_FILENAME = "AventurerosComboPoints.lua"
TOC_FILENAME = "SpellDraft.toc"
ANCHORS = ("AventurerosCustomSpellData.lua", "SpellData.lua")

COMBO_LUA = r'''-- Auto-generated by Aventureros de Azeroth.
-- Class 10 combo compatibility without replacing protected Blizzard APIs.

local AVENTUREROS_COMBO_PREFIX = "AventurerosCombo"
local ServerComboPoints = 0
local HasServerComboSync = false

if RegisterAddonMessagePrefix then
    RegisterAddonMessagePrefix(AVENTUREROS_COMBO_PREFIX)
end

-- Exposed only for diagnostics. The native GetComboPoints() is deliberately
-- left untouched because replacing it from addon code taints protected UI.
function AventurerosGetComboPoints()
    if HasServerComboSync then
        return ServerComboPoints
    end
    return 0
end

local function RenderComboPoints(points)
    if not ComboFrame then
        return
    end

    if points <= 0 then
        if ComboPoint1Highlight then ComboPoint1Highlight:SetAlpha(0) end
        if ComboPoint1Shine then ComboPoint1Shine:SetAlpha(0) end
        ComboFrame:Hide()
        return
    end

    ComboFrame:SetAlpha(1)
    ComboFrame:Show()

    for i = 1, 5 do
        local point = _G["ComboPoint" .. i]
        local highlight = _G["ComboPoint" .. i .. "Highlight"]
        local shine = _G["ComboPoint" .. i .. "Shine"]

        if point then
            point:Show()
        end
        if highlight then
            highlight:SetAlpha(i <= points and 1 or 0)
        end
        if shine then
            shine:SetAlpha(0)
        end
    end
end

-- Blizzard's stock ComboFrame reacts to UNIT_COMBO_POINTS by consulting the
-- native client API, which remains zero for class 10 and would immediately hide
-- our server-driven display. Stop only those two visual update events; this
-- frame is not a secure action frame.
if ComboFrame then
    ComboFrame:UnregisterEvent("UNIT_COMBO_POINTS")
    ComboFrame:UnregisterEvent("PLAYER_TARGET_CHANGED")
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("CHAT_MSG_ADDON")
frame:RegisterEvent("PLAYER_TARGET_CHANGED")
frame:SetScript("OnEvent", function(_, event, prefix, message)
    if event == "PLAYER_TARGET_CHANGED" then
        -- Hide immediately. The server will send the correct state for the new
        -- target on its next update tick.
        ServerComboPoints = 0
        RenderComboPoints(0)
        return
    end

    if event ~= "CHAT_MSG_ADDON" or prefix ~= AVENTUREROS_COMBO_PREFIX then
        return
    end

    local points = tonumber(message)
    if not points then
        return
    end

    points = math.floor(points)
    if points < 0 then
        points = 0
    elseif points > 5 then
        points = 5
    end

    ServerComboPoints = points
    HasServerComboSync = true
    RenderComboPoints(points)
end)
'''


class ComboPatchError(RuntimeError):
    pass


def patch_toc(toc_path: Path) -> bool:
    if not toc_path.is_file():
        raise ComboPatchError(f"SpellDraft TOC not found: {toc_path}")

    original = toc_path.read_text(encoding="utf-8")
    lines = [line for line in original.splitlines() if line.strip() != COMBO_FILENAME]

    insert_after = None
    for anchor in ANCHORS:
        for index, line in enumerate(lines):
            if line.strip() == anchor:
                insert_after = index
                break
        if insert_after is not None:
            break

    if insert_after is None:
        raise ComboPatchError(
            f"{toc_path}: neither AventurerosCustomSpellData.lua nor SpellData.lua was found"
        )

    lines.insert(insert_after + 1, COMBO_FILENAME)
    patched = "\n".join(lines) + "\n"
    if patched == original:
        return False

    backup = toc_path.with_name(toc_path.name + ".aventureros-original")
    if not backup.exists():
        shutil.copy2(toc_path, backup)
    toc_path.write_text(patched, encoding="utf-8")
    return True


def validate_install(addon_dir: Path) -> None:
    combo_path = addon_dir / COMBO_FILENAME
    toc_path = addon_dir / TOC_FILENAME

    if not combo_path.is_file():
        raise ComboPatchError(f"combo bridge was not written: {combo_path}")

    text = combo_path.read_text(encoding="utf-8")
    required = (
        'local AVENTUREROS_COMBO_PREFIX = "AventurerosCombo"',
        "function AventurerosGetComboPoints()",
        'ComboFrame:UnregisterEvent("UNIT_COMBO_POINTS")',
        'frame:RegisterEvent("CHAT_MSG_ADDON")',
        "RenderComboPoints(points)",
    )
    missing = [value for value in required if value not in text]
    if missing:
        raise ComboPatchError(
            f"{combo_path}: incomplete combo bridge: " + ", ".join(missing)
        )

    forbidden = (
        "local NativeGetComboPoints = GetComboPoints",
        "GetComboPoints = function",
    )
    present = [value for value in forbidden if value in text]
    if present:
        raise ComboPatchError(
            f"{combo_path}: protected API override still present: " + ", ".join(present)
        )

    toc_lines = [line.strip() for line in toc_path.read_text(encoding="utf-8").splitlines()]
    if toc_lines.count(COMBO_FILENAME) != 1:
        raise ComboPatchError(
            f"{toc_path}: expected exactly one {COMBO_FILENAME} entry"
        )


def patch_combo_ui(client_dir: Path) -> bool:
    addon_dir = client_dir / "Interface" / "AddOns" / "SpellDraft"
    if not addon_dir.is_dir():
        raise ComboPatchError(f"SpellDraft addon directory not found: {addon_dir}")

    combo_path = addon_dir / COMBO_FILENAME
    combo_changed = not combo_path.is_file() or combo_path.read_text(encoding="utf-8") != COMBO_LUA
    if combo_changed:
        combo_path.write_text(COMBO_LUA, encoding="utf-8")

    toc_changed = patch_toc(addon_dir / TOC_FILENAME)
    validate_install(addon_dir)
    return combo_changed or toc_changed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--client-dir", required=True, type=Path)
    args = parser.parse_args()

    try:
        changed = patch_combo_ui(args.client_dir.expanduser().resolve())
    except ComboPatchError as exc:
        raise SystemExit(f"SpellDraft combo UI patch aborted: {exc}") from exc

    print("SpellDraft Adventurer combo-point compatibility validated:")
    print(f"  status: {'patched' if changed else 'already valid'}")
    print(f"  addon file: {COMBO_FILENAME}")
    print("  native GetComboPoints(): untouched (no protected-UI taint)")
    print("  visual source: authoritative server combo state")
    print("  Blizzard ComboFrame remains the visible UI")
    print("  diagnostic API: AventurerosGetComboPoints()")


if __name__ == "__main__":
    main()
